import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from "../components/Header";
import MoviesCollection from "../components/MoviesCollection";

export default function Home({
  popularMovies,
  animatedMovies,
  adventureMovies,
  actionMovies
}) {
  return (
    <div className="">
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       
     <Header/>
     <MoviesCollection results={popularMovies} title="Best of All" />
     <MoviesCollection results={animatedMovies} title="Animated" />
     <MoviesCollection results={adventureMovies} title="Adventure" />
     <MoviesCollection results={actionMovies} title="Super Hero" />
     
     
    </div>
  );
}


export async function getServerSideProps(context) {
   

  const [
    popularMoviesRes,
    animatedMoviesRes,
    adventureMoviesRes,
    actionMoviesRes,
  ] = await Promise.all([
    fetch(
      `https://api.themoviedb.org/3/trending/all/day?api_key=${process.env.API_KEY}&language=en-US&page=1`
    ),
    fetch(
      `https://api.themoviedb.org/3/discover/movie?api_key=${process.env.API_KEY}&language=en-US&sort_by=popularity.desc&include_adult=true&include_video=true&page=4&with_watch_monetization_types=flatrate&with_genres=16`
    ),
    fetch(
      `https://api.themoviedb.org/3/discover/movie?api_key=${process.env.API_KEY}&language=en-US&sort_by=popularity.desc&include_adult=true&include_video=true&page=4&with_watch_monetization_types=flatrate&with_genres=12`
    ),
    fetch(
      `https://api.themoviedb.org/3/discover/movie?api_key=${process.env.API_KEY}&language=en-US&sort_by=popularity.desc&include_adult=true&include_video=true&page=4&with_watch_monetization_types=flatrate&with_genres=28`
    ),
  ]);
  const [popularMovies, animatedMovies, adventureMovies, actionMovies] =
    await Promise.all([
      popularMoviesRes.json(),
      animatedMoviesRes.json(),
      adventureMoviesRes.json(),
      actionMoviesRes.json(),
    ]);

  return {
    props: {
      popularMovies: popularMovies.results,
      animatedMovies: animatedMovies.results,
      adventureMovies: adventureMovies.results,
      actionMovies: actionMovies.results,
    },
  };
}