import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from "../components/Header";
import Link from 'next/link'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       
     <Header/>
     
     <div className="h-screen w-full flex flex-col-reverse px-24 py-36 bg-image" >
 <div className="text-white">
  <h1>Explore 50.000+ Movies</h1>
  <h2>Watch anywhere. Cancel anytime</h2>
  
  <Link href="/detail">
  <a>
   <button>Get Started</button>
  </a>
        </Link>
 </div>
</div>
    </div>
  );
}
